[package]
name = "RustAnalyse"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
rand = "0.9.2"
reqwest = "0.13.1"
tokio = { version = "1.49.0", features = ["full"] }
